from review_crawler import get_save_reviews_in_single_category

from product_crawler import get_save_product_info_in_all_category

get_save_product_info_in_all_category()
get_save_reviews_in_single_category(911006)